package Modelo;
// Generated 24-06-2018 1:21:23 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Postulacion generated by hbm2java
 */
public class Postulacion  implements java.io.Serializable {


     private String rut;
     private Comuna comuna;
     private String nombre;
     private String apppaterno;
     private String appmaterno;
     private Date fecnac;
     private Character sexo;
     private Character estadocivil;
     private Short hijos;
     private String telefono;
     private String email;
     private String direccion;
     private String educacion;
     private String renta;
     private Short sueldoLiquido;
     private Boolean enfermedad;
     private String estado;

    public Postulacion() {
    }
    
    public Postulacion(String rut){
        this.rut = rut;
    }

	
    public Postulacion(String rut, String nombre, String apppaterno, Date fecnac, String email, String direccion) {
        this.rut = rut;
        this.nombre = nombre;
        this.apppaterno = apppaterno;
        this.fecnac = fecnac;
        this.email = email;
        this.direccion = direccion;
    }
    public Postulacion(String rut, Comuna comuna, String nombre, String apppaterno, String appmaterno, Date fecnac, Character sexo, Character estadocivil, Short hijos, String telefono, String email, String direccion, String educacion, String renta, Short sueldoLiquido, Boolean enfermedad, String estado) {
       this.rut = rut;
       this.comuna = comuna;
       this.nombre = nombre;
       this.apppaterno = apppaterno;
       this.appmaterno = appmaterno;
       this.fecnac = fecnac;
       this.sexo = sexo;
       this.estadocivil = estadocivil;
       this.hijos = hijos;
       this.telefono = telefono;
       this.email = email;
       this.direccion = direccion;
       this.educacion = educacion;
       this.renta = renta;
       this.sueldoLiquido = sueldoLiquido;
       this.enfermedad = enfermedad;
       this.estado = estado;
    }
   
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public Comuna getComuna() {
        return this.comuna;
    }
    
    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApppaterno() {
        return this.apppaterno;
    }
    
    public void setApppaterno(String apppaterno) {
        this.apppaterno = apppaterno;
    }
    public String getAppmaterno() {
        return this.appmaterno;
    }
    
    public void setAppmaterno(String appmaterno) {
        this.appmaterno = appmaterno;
    }
    public Date getFecnac() {
        return this.fecnac;
    }
    
    public void setFecnac(Date fecnac) {
        this.fecnac = fecnac;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public Character getEstadocivil() {
        return this.estadocivil;
    }
    
    public void setEstadocivil(Character estadocivil) {
        this.estadocivil = estadocivil;
    }
    public Short getHijos() {
        return this.hijos;
    }
    
    public void setHijos(Short hijos) {
        this.hijos = hijos;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEducacion() {
        return this.educacion;
    }
    
    public void setEducacion(String educacion) {
        this.educacion = educacion;
    }
    public String getRenta() {
        return this.renta;
    }
    
    public void setRenta(String renta) {
        this.renta = renta;
    }
    public Short getSueldoLiquido() {
        return this.sueldoLiquido;
    }
    
    public void setSueldoLiquido(Short sueldoLiquido) {
        this.sueldoLiquido = sueldoLiquido;
    }
    public Boolean getEnfermedad() {
        return this.enfermedad;
    }
    
    public void setEnfermedad(Boolean enfermedad) {
        this.enfermedad = enfermedad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


