package Modelo;
// Generated 24-06-2018 1:21:23 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String us;
     private String clave;
     private String nombre;

    public Usuario() {
    }

    public Usuario(String us, String clave, String nombre) {
       this.us = us;
       this.clave = clave;
       this.nombre = nombre;
    }
   
    public String getUs() {
        return this.us;
    }
    
    public void setUs(String us) {
        this.us = us;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


